# Criando constantes
INDIVIDUAL_AMOUNT = 10
CROMOSSOME_LENGTH = 8
GENES_KEY = "genes"
SCORE_KEY = "score"
REMOVED_INDIVIDUAL_AMOUNT = INDIVIDUAL_AMOUNT - 1
CROSSING_OVER_SPLIT_LENGTH = int(CROMOSSOME_LENGTH/2)
CROSSING_OVER_INDIVIDUAL_AMOUNT = int(INDIVIDUAL_AMOUNT/3)
GENERATION_SURVIVOR_AMOUNT = int(INDIVIDUAL_AMOUNT/4)
GENERATION_KILL_AMOUNT = INDIVIDUAL_AMOUNT - GENERATION_SURVIVOR_AMOUNT
