# Criando constantes
INDIVIDUAL_NUMBER = 10
CROMOSSOME_LENGTH = 8
GENES_KEY = "genes"
SCORE_KEY = "score"
REMOVED_INDIVIDUAL_AMOUNT = INDIVIDUAL_NUMBER - 1
CROSSING_OVER_SPLIT_LENGTH = CROMOSSOME_LENGTH/2
