# Criando constantes
INDIVIDUAL_AMOUNT = 10
CROMOSSOME_LENGTH = 8
REMOVED_INDIVIDUAL_AMOUNT = INDIVIDUAL_AMOUNT - 4
SURVIVING_INDIVIDUAL_AMOUNT = INDIVIDUAL_AMOUNT - REMOVED_INDIVIDUAL_AMOUNT
CROSSING_OVER_INDIVIDUAL_AMOUNT = SURVIVING_INDIVIDUAL_AMOUNT
CROSSING_OVER_SPLIT_LENGTH = int(CROMOSSOME_LENGTH/2)

# Constantes que não faz diferença mudar
GENES_KEY = "genes"
SCORE_KEY = "score"
